/**:
  state_estimator:
    ros__parameters:
      use_ignition_tf: False
      mocap_topic: "/mocap/rigid_bodies"
      twist_smooth_filter_cte: 0.1
      orientation_smooth_filter_cte: 0.1
cf0:
  state_estimator:
    ros__parameters:
      rigid_body_name: "'1'"
cf1:
  state_estimator:
    ros__parameters:
      rigid_body_name: "'2'"
cf2:
  state_estimator:
    ros__parameters:
      rigid_body_name: "'3'"