/**:
  platform_crazyflie:
    ros__parameters:
      cmd_freq: 100.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      external_odom: true  # Availability of external odometry
      external_odom_topic: "self_localization/pose" # External odometry topic name
      controller_type: 1  # Controller type Any(0), PID(1), Mellinger(2), INDI(3)
      estimator_type: 2 # Estimator type Any(0), complementary(1), kalman(2)
      multi_ranger_deck: false # Availability of multi ranger deck
  state_estimator_mocap_pose:
    ros__parameters:
      use_ignition_tf: False
      rigid_body_name: "root"
      mocap_topic: "/rigid_bodies"
  controller_manager_pid_speed_controller:
    ros__parameters:
      cmd_freq: 100.0  # Hz of platform commands send
      info_freq: 10.0  # Hz of platform info publish
      odom_frame_id: "odom"
      base_frame_id: "base_link"
      use_bypass: true
      controller:
        proportional_limitation: true
        position_control:
          reset_integral: false
          antiwindup_cte: 1.0
          alpha: 0.3
          kp:
            x: 0.4
            y: 0.4
            z: 0.4
          kd:
            x: 0.0
            y: 0.0
            z: 0.0
          ki:
            x: 0.0001
            y: 0.0001
            z: 0.0001
        speed_control:
          reset_integral: false
          antiwindup_cte : 1.0
          alpha: 0.3
          kp:
            x: 1.0
            y: 1.0
            z: 1.0
          kd:
            x: 0.0
            y: 0.0
            z: 0.0
          ki:
            x: 0.0
            y: 0.0
            z: 0.0
        speed_in_a_plane_control:
          reset_integral: false
          antiwindup_cte: 1.0
          alpha: 0.3
          height:
            kp: 1.0
            kd: 0.0
            ki: 0.0
          speed:
            kp:
              x: 0.0
              y: 0.0
            kd:
              x: 0.0
              y: 0.0
            ki:
              x: 0.0
              y: 0.0
        trajectory_control:
          reset_integral: false
          antiwindup_cte : 1.0
          alpha: 0.3
          kp:
            x: 0.4
            y: 0.4
            z: 0.4
          kd:
            x: 0.0001
            y: 0.0001
            z: 0.0001
          ki:
            x: 0.0
            y: 0.0
            z: 0.0
        yaw_control:
          reset_integral: false
          antiwindup_cte : 1.0
          alpha: 0.3
          kp: 1.0
          kd: 0.001
          ki: 0.0
