/**:
  ros__parameters:
    default_takeoff_plugin: "takeoff_plugin_speed"
    default_takeoff_altitude: 0.5  # [m]
    default_takeoff_speed: 0.2     # [m/s]
    takeoff_height_threshold: 0.1  # [m]
    frame_id_pose: "/earth"
    frame_id_twist: "/earth"